In [4]:
import numpy as np
arr = np.arange(11)
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [9]:
A = np.random.randn(10)
A

array([ 1.21583185, -0.73006152, -1.69672746, -1.47827513, -0.57119695,
        1.38085178,  0.28927763, -0.6244816 , -0.48166662, -0.65838184])

In [10]:
B = np.random.randn(10)
B

array([-0.98064671, -0.5264099 ,  0.48826026,  0.17749541,  0.49290726,
       -0.71450167, -0.25342575, -0.02821659,  0.71595457,  0.90054119])

In [11]:
#Binary Function
np.add(A,B)

array([ 0.23518514, -1.25647142, -1.2084672 , -1.30077972, -0.07828969,
        0.66635011,  0.03585188, -0.65269818,  0.23428795,  0.24215935])

In [12]:
np.maximum(A,B)

array([ 1.21583185, -0.5264099 ,  0.48826026,  0.17749541,  0.49290726,
        1.38085178,  0.28927763, -0.02821659,  0.71595457,  0.90054119])

In [13]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True